### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by aromanocohen** [bojand/mailgun-js#196] opened 2018-03-02 01:28 UTC
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.7.12
2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
0.12.5
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
yes
4) Sample source code or steps to reproduce
require('mailgun-js')({apiKey: apiKey, domain: domain});
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Hi, the problem is that a module that is used by mailgun-js, is using another module that  has ECMASCRIPT CODE 6 and because I'am using node 0.12.5, node can not parse the code. Pleas help me understand how to solve it. I think this is a package.json Issue.

nudniq-0 antes de generar el mailgun
nudniq-0 /home/ec2-user/test2/fastpass/node_modules/ast-types/def/flow.js:247
nudniq-0   ].forEach(typeName => {
nudniq-0                      ^^
nudniq-0 SyntaxError: Unexpected token =>
nudniq-0     at exports.runInThisContext (vm.js:73:16)
nudniq-0     at Module._compile (module.js:443:25)
nudniq-0     at Object.Module._extensions..js (module.js:478:10)
nudniq-0     at Module.load (module.js:355:32)
nudniq-0     at Function.Module._load (module.js:310:12)
nudniq-0     at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
nudniq-0     at Module.require (module.js:365:17)
nudniq-0     at require (module.js:384:17)
nudniq-0     at Object.<anonymous> (/home/ec2-user/test2/fastpass/node_modules/ast-types/main.js:13:3)
nudniq-0     at Module._compile (module.js:460:26)
nudniq-0     at Object.Module._extensions..js (module.js:478:10)
nudniq-0     at Module.load (module.js:355:32)
nudniq-0     at Function.Module._load (module.js:310:12)
nudniq-0     at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
nudniq-0     at Module.require (module.js:365:17)
nudniq-0     at require (module.js:384:17)
nudniq-0 freetype.js:1
nudniq-0 aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}))}els
nudniq-0                                                                     ^
nudniq-0 /home/ec2-user/test2/fastpass/node_modules/ast-types/def/flow.js:247
nudniq-0   ].forEach(typeName => {
nudniq-0                      ^^
nudniq-0 SyntaxError: Unexpected token =>
nudniq-0     at exports.runInThisContext (vm.js:73:16)
nudniq-0     at Module._compile (module.js:443:25)
nudniq-0     at Object.Module._extensions..js (module.js:478:10)
nudniq-0     at Module.load (module.js:355:32)
nudniq-0     at Function.Module._load (module.js:310:12)
nudniq-0     at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
nudniq-0     at Module.require (module.js:365:17)
nudniq-0     at require (module.js:384:17)
nudniq-0     at Object.<anonymous> (/home/ec2-user/test2/fastpass/node_modules/ast-types/main.js:13:3)
nudniq-0     at Module._compile (module.js:460:26)
nudniq-0     at Object.Module._extensions..js (module.js:478:10)

I have been operating with mailgun-js very well for more than two years.

Pleas Help me

**Comment by bojand** [comment] 2018-03-02 12:32
Hmm nothing in that stack trace seem to indicate that the exception is coming from mailgun-js? Can you provide a reproducible code sample please? Regardless, 0.12.0 is [**End-of-Life**](https://github.com/nodejs/Release#release-schedule) so who knows what else can be going wrong there. You _really_ should update.

**Comment by lmachens** [comment] 2018-03-05 10:12
I have a similar issue with Node 8.9.4 and mailgun 0.16.0.
Happens only in Internet Explorer and Edge.
Error message: 
`Syntax error` in line `class Mailgun`.

**Comment by devendrasr** [comment] 2018-03-27 06:27
@bojand Please use below stake trace for above issue (The reason behind this exception is mailgun has been using syntax for latest javascript version and we are using node version 0.12.7)-
```  
root@f6be8399def7:/var/www/api/core# node test-email.js 
/var/www/api/core/node_modules/mailgun-js/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/degenerator/node_modules/ast-types/def/flow.js:247
  ].forEach(typeName => {
                     ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/api/core/node_modules/mailgun-js/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/degenerator/node_modules/ast-types/main.js:13:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
root@f6be8399def7:/var/www/api/core# node -v
v0.12.7
root@f6be8399def7:/var/www/api/core# vim /var/www/api/core/node_modules/mailgun-js/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/degenerator/node_modules/ast-types/def/flow.js

**Comment by bojand** [comment] 2018-03-28 12:30
Examining the stack trace... If you follow the versions specified as dependencies from `mailgun-js@0.7.12` eventually you see that [degenerator depends on `0.x.x` if `ast-types`](https://github.com/TooTallNate/node-degenerator/blob/1.0.4/package.json). I am guessing, or it appears, you did not [shrinkwrap](https://docs.npmjs.com/files/shrinkwrap.json) your dependencies and at some point when you reinstalled everything it picked up new version of `ast-types` with the new syntax and things broke. Note since `ast-types` is at `0.x.x` range and `degenrerator` depends on it, really for ast-types anything goes as per [semver spec](https://semver.org/). So that's really the issue. One option you could try is somehow lock down the `ast-types` dependency to a working version. But my advice still stands... you _need_ to update your platform. `0.12.0` is [**End-of-Life**](https://github.com/nodejs/Release#release-schedule) and it is an unmaintained and insecure target. `4.x` will be **EOL** at the end of April. At least you should start using 6.x which will enter maintenance mode in May, but I would highly recommend the current LTS `8.x`. and that you follow LTS in the future. The latest version of this module requires Node `6`. In addition I suggest you explore locking down your dependencies so you're not open to fluctuating deployments. Some documentation:

- https://docs.npmjs.com/files/package-locks
- https://docs.npmjs.com/cli/shrinkwrap
- https://docs.npmjs.com/cli/ci

Closing as `Wont Fix` as the problem is identified and there is nothing that we can do. If it still persists once you've updated Node version to one that's supported feel free to re-open.

**Closed** 2018-03-28 12:31 UTC
Labels: wontfix
