### ISSUE TITLE
Invalid parameter type. renameProperty must be of type: undefined.

### ISSUE THREAD

**Issue by programmerpsk** [bojand/mailgun-js#192] opened 2018-01-28 08:04 UTC
1) What version of the module is the issue happening on? Does the issue happen on latest version?
**0.14.2**
2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
**6.10.0**
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
**yes**

4) Sample source code or steps to reproduce
`{ from: '"Bio-soft" <skpark@biosoft.kaist.ac.kr>',
  to: 'prograrmmerpsk@gmail.com',
  subject: 'Please change your password',
  html: '...'`

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

there is a error like 'Invalid parameter type. renameProperty must be of type: undefined.' when I send a email using mailgun-js function.

function like this.

`mailgun.messages().send(data, function (error, body) {
      if(error) {
        console.log(error)
      } else {
        return res.end('success');
      }
    });`

**Comment by bojand** [comment] 2018-02-01 01:18
Hello, can you please provide a more detailed report with a stack trace. I was not able to reproduce this with the specific version of node and module. Thanks.

**Comment by bojand** [comment] 2018-03-28 12:37
Closing due to lack of follow-up information.

**Closed by bojand** 2018-03-28 12:37 UTC
