### ISSUE TITLE
[feature request] add types support; for typescript

### ISSUE THREAD

**Issue by dheerajbhaskar** [bojand/mailgun-js#121] opened 2016-12-16 20:59 UTC
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.7.14, yes
2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
v6.4.0, win 10 pro x64
3) Does the action work when you manually perform request against mailgun using curl (or other means)?
not applicable
4) Sample source code or steps to reproduce
not applicable
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Add type support so that when one does `npm install -D @types/mailgun-js` the types get installed;
(OR) package it along with mailgun-js package itself.

Official Guide:  https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I'm new to this package. I shall do it if I find time

PS: I've no affiliation with TS, just a user

**Comment by bojand** [comment] 2017-01-24 01:03
Duplicate of #100

**Closed** 2017-04-11 02:10 UTC
Labels: duplicate, enhancement

**Comment by Allan-Nava** [comment] 2020-05-22 06:26
> 1. What version of the module is the issue happening on? Does the issue happen on latest version?
>    0.7.14, yes
> 2. What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
>    v6.4.0, win 10 pro x64
> 3. Does the action work when you manually perform request against mailgun using curl (or other means)?
>    not applicable
> 4. Sample source code or steps to reproduce
>    not applicable
>    (Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
> 
> Add type support so that when one does `npm install -D @types/mailgun-js` the types get installed;
> (OR) package it along with mailgun-js package itself.
> 
> Official Guide: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
> 
> I'm new to this package. I shall do it if I find time
> 
> PS: I've no affiliation with TS, just a user

Now it works with typescript?
